export const GET_ARTISTS_REQUEST = "GET_ARTISTS_REQUEST";
export const GET_ARTISTS_SUCCESS = "GET_ARTISTS_SUCCESS";
export const GET_ARTISTS_FAILURE = "GET_ARTISTS_FAILURE";

export const GET_ARTIST_EVENTS_REQUEST = "GET_ARTIST_DETAILS_REQUEST";
export const GET_ARTIST_EVENTS_SUCCESS = "GET_ARTIST_DETAILS_SUCCESS";
export const GET_ARTIST_EVENTS_FAILURE = "GET_ARTIST_DETAILS_FAILURE";