export const GET_AIRLINES_REQUEST = "GET_AIRLINES_REQUEST";
export const GET_AIRLINES_SUCCESS = "GET_AIRLINES_SUCCESS";
export const GET_AIRLINES_FAILURE = "GET_AIRLINES_FAILURE";

export const GET_AIRLINE_REQUEST = "GET_AIRLINE_REQUEST";
export const GET_AIRLINE_SUCCESS = "GET_AIRLINE_SUCCESS";
export const GET_AIRLINE_FAILURE = "GET_AIRLINE_FAILURE";

export const CLEAR_AIRLINE = "CLEAR_AIRLINE";